Add support for GKE boot disk type in node configuration
castai/terraform-provider-castai pull request #180
Opened 2023-06-29 15:15 UTC by apasyniuk

2023-07-03 09:38 UTC, fals approved these changes

2023-07-03 10:24 UTC, Narunas-K requested changes
As new field was added, let's include it to acceptance test as well. E.g. https://github.com/castai/terraform-provider-castai/blob/master/castai/resource_node_configuration_test.go#L44-L48

2023-07-03 15:44 UTC, apasyniuk commented
> As new field was added, let's include it to acceptance test as well. E.g. https://github.com/castai/terraform-provider-castai/blob/master/castai/resource_node_configuration_test.go#L44-L48

@Narunas-K It seems like this is EKS specific test. To verify this new field in acceptance tests, a new test is required that will create a GKE cluster. Should I then add a new test?

2023-07-04 07:53 UTC, Narunas-K approved these changes

2023-07-04 08:55 UTC, merged